Update `stage_dem` to insert longer description (with license info) in output VRT (#88)
* Update `stage_dem` to insert longer description in VRT

Update the `stage_dem` workflow to insert a more detailed description
(including license info) in the output VRT file.

* Update some `str` -> `bytes` conversions

Adds a helper function `nisar.products.utils.to_bytes()` that may be
used to convert arbitrary Unicode strings (or arrays of such strings) to
bytestrings in UTF-8 encoding.

Unicode strings are always encoded as fixed-length bytestrings in UTF-8
encoding in NISAR HDF5 products.

Previously, this conversion was always implemented using the
`numpy.bytes_(...)` function. However, this function raises an error if
the input string contains non-ASCII characters.

```python
>>> import numpy as np
>>> s = "The Copernicus DEM 30m was produced using Copernicus WorldDEM-30 © DLR e.V. 2010-2014 and © Airbus Defence and Space GmbH 2014-2018 provided under COPERNICUS by the European Union and ESA; all rights reserved."
>>> np.bytes_(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 65: ordinal not in range(128)
```

Since user-provided input may contain arbitrary Unicode characters and
since the DEM description/license is expected to contain non-ASCII
characters, we should use a different approach when converting these
strings to bytes.

* Use "dem_description" name for tiff files

* Remove `max_size_bytes`; Parse the entire README

* Fix unit test

* Fix missing period in older README versions